(define ssax-sxml (getenv "SSAXLIB"))
(load (string-append ssax-sxml "/libs/gambit/common.scm"))
(load (string-append ssax-sxml "/libs/gambit/myenv.scm"))
(load (string-append ssax-sxml "/libs/input-parse.scm"))
(load (string-append ssax-sxml "/libs/srfi-13-local.scm"))
(load (string-append ssax-sxml "/ssax/char-encoding.scm"))
(load (string-append ssax-sxml "/ssax/SSAX-code.scm"))
(load (string-append ssax-sxml "/ssax/SXML-tree-trans.scm"))
(load (string-append ssax-sxml "/sxml-tools/xpath-parser.scm"))
(load (string-append ssax-sxml "/sxml-tools/sxpath.scm"))
(load (string-append ssax-sxml "/sxml-tools/sxpathlib.scm"))
(load (string-append ssax-sxml "/sxml-tools/sxpath-ext.scm"))
(load (string-append ssax-sxml "/sxml-tools/txpath.scm"))

(load "common/xinclude.scm")

;(display (command-line))
(define xml-file (cadr (member "--xml" (command-line))))
(define doc (SSAX:XML->SXML (open-input-file xml-file) '()))
;(display xml-file)
;(newline)
;(pp doc (current-output-port))
(pp (resolve-xincludes doc (path-directory xml-file)) (current-output-port))
(exit)
