(define (texml-serialize doc cout)
  (letrec ((st `(
      (texml . ,sxslt-id)
      (cmd *preorder* . ,(lambda (cmd-tag cmd-name . rest)
                           (cout #\\ cmd-name)
                           (if (null? rest)
	 (cout "{}")
	 (pre-post-order rest st))))
      (gr *preorder* . ,(lambda (gr-tag . rest)
                          (cout #\{)
                          (pre-post-order rest st)
                          (cout #\})))
      (env *preorder* . ,(lambda (env-tag env-name . rest)
                          (cout "\\begin{" env-name #\})
                          (pre-post-order rest st)
                          (cout "\\end{" env-name #\})))
      (*text* . ,(lambda (dummy s) (cout s)))
      )))
    (pre-post-order doc st)
    (cout #\newline)))
